import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import CustomCursor from "../components/CustomCursor";

const humane = localFont({
  src: './fonts/Humane-VF.ttf',
  variable: '--font-humane',
});

const manuscribe = localFont({
  src: [
    {
      path: './fonts/ManuscribeFree-Regular.otf',
      style: 'normal',
    },
    {
      path: './fonts/ManuscribeFree-Italic.otf',
      style: 'italic',
    },
  ],
  variable: '--font-manuscribe',
});

const glusp = localFont({
  src: './fonts/OTF® Glusp.ttf',
  variable: '--font-glusp',
});

const emberly = localFont({
  src: './fonts/CYR_CT_OP_Emberly Regular [wdth,wght]-VF.ttf',
  variable: '--font-emberly',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${humane.variable} ${manuscribe.variable} ${glusp.variable} ${emberly.variable} antialiased cursor-none`}
      >
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}
